'use client';

/**
 * components/features/practice/coaching-panel.tsx
 *
 * Right-side coaching panel during a Practice Mode session.
 * Displays live coaching tips as the conversation progresses.
 * Tips are generated by the AI as coach_notes and passed in as props.
 *
 * Also shows the active methodology names so the user knows which
 * frameworks are guiding the coaching feedback.
 */

import { Lightbulb, AlertCircle, ThumbsUp } from 'lucide-react';

/** Shape of a single coaching note (matches the JSONB schema in practice_sessions) */
export interface CoachNote {
  id: string;
  timestamp: Date;
  type: 'tip' | 'warning' | 'praise';
  stage?: string;
  note: string;
}

interface CoachingPanelProps {
  /** Coaching notes generated during the session */
  notes: CoachNote[];
  /** Names of the active methodologies (displayed as context) */
  activeMethodologyNames: string[];
}

/** Icon and color for each note type */
const NOTE_STYLES = {
  tip: {
    icon: Lightbulb,
    bg: 'bg-blue-500/10',
    border: 'border-blue-500/20',
    text: 'text-blue-600',
    label: 'Tip',
  },
  warning: {
    icon: AlertCircle,
    bg: 'bg-amber-500/10',
    border: 'border-amber-500/20',
    text: 'text-amber-600',
    label: 'Watch out',
  },
  praise: {
    icon: ThumbsUp,
    bg: 'bg-green-500/10',
    border: 'border-green-500/20',
    text: 'text-green-600',
    label: 'Well done',
  },
};

/**
 * CoachingPanel — Live coaching sidebar.
 * Shows the most recent coaching notes at the top (reverse chronological).
 */
export function CoachingPanel({ notes, activeMethodologyNames }: CoachingPanelProps) {
  // Show latest notes first
  const reversedNotes = [...notes].reverse();

  return (
    <div className="flex h-full flex-col gap-4 p-4">
      {/* Active methodologies */}
      {activeMethodologyNames.length > 0 && (
        <div>
          <p className="mb-1.5 text-xs font-medium uppercase tracking-wider text-foreground/50">
            Active Frameworks
          </p>
          <div className="flex flex-wrap gap-1.5">
            {activeMethodologyNames.map((name) => (
              <span
                key={name}
                className="rounded-full border border-brand-600/30 bg-brand-600/10 px-2 py-0.5 text-xs font-medium text-brand-600"
              >
                {name}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* Coaching notes header */}
      <div className="flex items-center justify-between">
        <p className="text-xs font-medium uppercase tracking-wider text-foreground/50">
          Live Coaching
        </p>
        {notes.length > 0 && (
          <span className="text-xs text-foreground/40">{notes.length} note{notes.length !== 1 ? 's' : ''}</span>
        )}
      </div>

      {/* Notes list */}
      <div className="flex-1 space-y-3 overflow-y-auto">
        {reversedNotes.length === 0 && (
          <div className="flex h-full items-center justify-center text-center">
            <p className="text-sm text-foreground/40 max-w-[180px]">
              Coaching tips will appear here as you practice.
            </p>
          </div>
        )}

        {reversedNotes.map((note) => {
          const style = NOTE_STYLES[note.type];
          const Icon = style.icon;

          return (
            <div
              key={note.id}
              className={`rounded-lg border px-3 py-2.5 ${style.bg} ${style.border}`}
            >
              <div className={`mb-1 flex items-center gap-1.5 text-xs font-semibold ${style.text}`}>
                <Icon className="h-3.5 w-3.5" />
                <span>{style.label}</span>
                {note.stage && (
                  <span className="ml-auto font-normal text-foreground/50">{note.stage}</span>
                )}
              </div>
              <p className="text-sm text-foreground/80 leading-snug">{note.note}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
}
