/**
 * types/database-features.ts
 *
 * Feature-specific Supabase table types — email composition, call history,
 * user notes, practice sessions, strategies library.
 *
 * Core/infrastructure table types live in database-core.ts.
 */

/* ──────────────────── Email Composition Feature ──────────────────── */

/** Row in `email_conversations` — AI-assisted email drafting sessions */
export interface EmailConversation {
  id: string;
  user_id: string;
  title: string | null;
  /** Ordered array of chat-style messages between user and AI */
  messages: unknown[];
  draft_email: string | null;
  previous_communication: string | null;
  /** Which methodology guided email composition */
  methodology_id: string | null;
  created_at: string;
  updated_at: string;
}

/* ──────────────────── Call History / Analyzer ────────────────────── */

/** Row in `call_history` — recorded/uploaded calls with AI analysis */
export interface CallHistory {
  id: string;
  user_id: string;
  duration: number | null;
  transcript: string | null;
  /** Structured summary generated by the Call Analyzer feature */
  summary: Record<string, unknown>;
  /** AI-generated improvement suggestions */
  suggestions: Record<string, unknown>;
  /** User-pinned insights from the analysis */
  pinned_insights: Record<string, unknown>;
  score: number | null;
  follow_up_email: string | null;
  /** Which methodology was active when this call was analyzed */
  methodology_id: string | null;
  /** Per-dimension scores from the methodology's scoring rubric */
  methodology_scores: unknown[];
  created_at: string;
  updated_at: string;
}

/* ───────────────────────── User Notes ───────────────────────────── */

/** Row in `user_notes` — personal notes optionally linked to calls */
export interface UserNote {
  id: string;
  user_id: string;
  title: string | null;
  content: string | null;
  source: string | null;
  starred: boolean;
  segment: string | null;
  skill: string | null;
  call_type: string | null;
  ai_insight: string | null;
  linked_call_id: string | null;
  linked_call_name: string | null;
  last_viewed_at: string | null;
  created_at: string;
  updated_at: string;
}

/* ────────────────────── Practice Mode ───────────────────────────── */

/** Row in `practice_sessions` — AI roleplay training sessions */
export interface PracticeSession {
  id: string;
  user_id: string;
  persona_type: string | null;
  difficulty: number | null;
  score: number | null;
  duration_seconds: number | null;
  /** Full conversation history of the practice session */
  messages: unknown[];
  /** AI-generated feedback on the user's performance */
  feedback: Record<string, unknown>;
  /** Methodology stage reached (methodology-specific, no longer Paul Cherry only) */
  commitment_stage: string | null;
  /** Which methodology was active during this practice session */
  methodology_id: string | null;
  /** Per-dimension scores from the methodology's scoring rubric */
  methodology_scores: unknown[];
  created_at: string;
}

/* ────────────────────── Context Packs ───────────────────────────── */

/** Row in `context_packs` — industry/domain overlay packs that enrich AI coaching context */
export interface ContextPack {
  id: string;
  name: string;
  /** URL-safe identifier, e.g. "b2b-saas-sales" */
  slug: string;
  description: string | null;
  /** Appended to Layer 1 of the system prompt to inject industry identity */
  identity_overlay: string | null;
  /** Pre-built practice scenarios for this industry — array of scenario objects */
  persona_templates: unknown[];
  /** Industry-specific vocabulary merged with methodology vocab — key→value pairs */
  vocabulary_overlay: Record<string, string>;
  /** Methodology UUIDs that work well with this context pack */
  suggested_methodology_ids: string[];
  /** Emoji or icon shown in the selector UI */
  icon: string | null;
  is_active: boolean;
  created_at: string;
}

/* ──────────────────── Session Configurations ────────────────────── */

/** Row in `session_configurations` — saved session presets (methodology + context pack) */
export interface SessionConfiguration {
  id: string;
  user_id: string;
  /** Which SAIL feature this config applies to */
  session_type: 'practice' | 'live-call' | 'analyzer';
  /** Array of methodology IDs selected for this configuration */
  methodology_ids: string[];
  /** Optional industry context pack linked to this configuration */
  context_pack_id: string | null;
  /** Human-readable label, e.g. "BANT + MEDPIC for SaaS" */
  name: string | null;
  /** Whether this is the default preset shown when opening the session type */
  is_default: boolean;
  created_at: string;
  updated_at: string;
}

/* ─────────────────── Live Call Sessions ─────────────────────────── */

/** A single coaching event emitted during a live call */
export interface CoachingEvent {
  id: string;
  timestamp: string;
  type: 'tip' | 'alert';
  content: string;
}

/** Row in `live_call_sessions` — real-time coaching session with transcript + coaching events */
export interface LiveCallSession {
  id: string;
  user_id: string;
  /** Optional link to a saved session configuration */
  session_config_id: string | null;
  status: 'active' | 'completed';
  /** Full conversation transcript — array of { speaker, text, timestamp } objects */
  transcript: unknown[];
  /** Coaching tips/alerts emitted during the call */
  coaching_events: CoachingEvent[];
  /** Dynamic checklist — key → boolean, updated as topics are covered */
  checklist_state: Record<string, boolean>;
  /** Qualification data extracted from transcript — key → extracted value */
  qualification_data: Record<string, unknown>;
  duration_seconds: number | null;
  created_at: string;
  completed_at: string | null;
  /** Industry context pack active during this session */
  context_pack_id: string | null;
}

/* ────────────────────── Strategies Library ───────────────────────── */

/** Row in `strategies` — methodology technique reference cards */
export interface Strategy {
  id: string;
  title: string;
  category: string | null;
  description: string | null;
  content: string | null;
  prompt_type: string | null;
  /** Worked examples demonstrating the technique */
  examples: unknown[];
  /** Searchable tags for filtering */
  tags: string[];
  /** Parent methodology this technique belongs to */
  methodology_id: string | null;
  /** True if this technique applies across all methodologies */
  is_universal: boolean;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
