/**
 * types/database-features.ts
 *
 * Feature-specific Supabase table types — email composition, call history,
 * user notes, practice sessions, strategies library.
 *
 * Core/infrastructure table types live in database-core.ts.
 */

/* ──────────────────── Email Composition Feature ──────────────────── */

/** Row in `email_conversations` — AI-assisted email drafting sessions */
export interface EmailConversation {
  id: string;
  user_id: string;
  title: string | null;
  /** Ordered array of chat-style messages between user and AI */
  messages: unknown[];
  draft_email: string | null;
  previous_communication: string | null;
  created_at: string;
  updated_at: string;
}

/* ──────────────────── Call History / Analyzer ────────────────────── */

/** Row in `call_history` — recorded/uploaded calls with AI analysis */
export interface CallHistory {
  id: string;
  user_id: string;
  duration: number | null;
  transcript: string | null;
  /** Structured summary generated by the Call Analyzer feature */
  summary: Record<string, unknown>;
  /** AI-generated improvement suggestions */
  suggestions: Record<string, unknown>;
  /** User-pinned insights from the analysis */
  pinned_insights: Record<string, unknown>;
  score: number | null;
  follow_up_email: string | null;
  created_at: string;
  updated_at: string;
}

/* ───────────────────────── User Notes ───────────────────────────── */

/** Row in `user_notes` — personal notes optionally linked to calls */
export interface UserNote {
  id: string;
  user_id: string;
  title: string | null;
  content: string | null;
  source: string | null;
  starred: boolean;
  segment: string | null;
  skill: string | null;
  call_type: string | null;
  ai_insight: string | null;
  linked_call_id: string | null;
  linked_call_name: string | null;
  last_viewed_at: string | null;
  created_at: string;
  updated_at: string;
}

/* ────────────────────── Practice Mode ───────────────────────────── */

/** Row in `practice_sessions` — AI roleplay training sessions */
export interface PracticeSession {
  id: string;
  user_id: string;
  persona_type: string | null;
  difficulty: number | null;
  score: number | null;
  duration_seconds: number | null;
  /** Full conversation history of the practice session */
  messages: unknown[];
  /** AI-generated feedback on the user's performance */
  feedback: Record<string, unknown>;
  /** Paul Cherry commitment stage: Sure → Want To → Have To */
  commitment_stage: string | null;
  created_at: string;
}

/* ────────────────────── Strategies Library ───────────────────────── */

/** Row in `strategies` — Paul Cherry methodology reference cards */
export interface Strategy {
  id: string;
  title: string;
  category: string | null;
  description: string | null;
  content: string | null;
  prompt_type: string | null;
  /** Worked examples demonstrating the technique */
  examples: unknown[];
  /** Searchable tags for filtering */
  tags: string[];
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}
