/**
 * types/database.ts
 *
 * Barrel file that re-exports every Supabase table type and provides the
 * top-level `Database` type used by the Supabase client generic parameter.
 *
 * Split across two modules to stay under the 200-line limit:
 *   - database-core.ts    → auth, roles, profiles, AI config, infra tables
 *   - database-features.ts → email, calls, notes, practice, strategies
 */

/* ── Re-export all individual table types for direct import ── */

export type {
  AuthorizedMember,
  UserRole,
  UserProfile,
  AiFeatureKey,
  AiProviderKey,
  AiProviderConfig,
  TokenUsageLog,
  AuditLog,
  WebhookEvent,
  BackgroundJob,
  FeatureFlag,
  AppSetting,
} from './database-core';

export type {
  EmailConversation,
  CallHistory,
  UserNote,
  PracticeSession,
  Strategy,
  ContextPack,
  SessionConfiguration,
  LiveCallSession,
  CoachingEvent,
} from './database-features';

export type {
  Methodology,
  UserMethodologyPreference,
} from './methodology';

export type {
  MethodologyEvent,
} from './coaching-events';

/* ── Import concrete types needed for the Database wrapper ── */

import type {
  AuthorizedMember,
  UserRole,
  UserProfile,
  AiProviderConfig,
  TokenUsageLog,
  AuditLog,
  WebhookEvent,
  BackgroundJob,
  FeatureFlag,
  AppSetting,
} from './database-core';

import type {
  EmailConversation,
  CallHistory,
  UserNote,
  PracticeSession,
  Strategy,
  ContextPack,
  SessionConfiguration,
  LiveCallSession,
} from './database-features';

import type { Methodology, UserMethodologyPreference } from './methodology';
import type { MethodologyEvent } from './coaching-events';

/* ── Helper: generates Row / Insert / Update shapes per table ── */

/**
 * Utility that produces the standard shape Supabase expects for each table.
 * Row   = what you get back from a SELECT
 * Insert = what you pass to an INSERT (all fields optional except non-nullable ones)
 * Update = what you pass to an UPDATE (all fields optional)
 */
interface TableDefinition<T> {
  Row: T;
  Insert: Partial<T>;
  Update: Partial<T>;
}

/* ── Top-level Database type for `createClient<Database>()` ── */

/**
 * Pass this as the generic to `createClient<Database>()` so the Supabase
 * JS client returns strongly-typed rows for every query.
 *
 * Example:
 *   import { createClient } from '@supabase/supabase-js';
 *   import type { Database } from '@/types/database';
 *   const supabase = createClient<Database>(url, key);
 */
export interface Database {
  public: {
    Tables: {
      authorized_members: TableDefinition<AuthorizedMember>;
      user_roles: TableDefinition<UserRole>;
      user_profiles: TableDefinition<UserProfile>;
      ai_provider_configs: TableDefinition<AiProviderConfig>;
      token_usage_logs: TableDefinition<TokenUsageLog>;
      audit_logs: TableDefinition<AuditLog>;
      webhook_events: TableDefinition<WebhookEvent>;
      background_jobs: TableDefinition<BackgroundJob>;
      feature_flags: TableDefinition<FeatureFlag>;
      app_settings: TableDefinition<AppSetting>;
      email_conversations: TableDefinition<EmailConversation>;
      call_history: TableDefinition<CallHistory>;
      user_notes: TableDefinition<UserNote>;
      practice_sessions: TableDefinition<PracticeSession>;
      strategies: TableDefinition<Strategy>;
      methodologies: TableDefinition<Methodology>;
      user_methodology_preferences: TableDefinition<UserMethodologyPreference>;
      methodology_events: TableDefinition<MethodologyEvent>;
      context_packs: TableDefinition<ContextPack>;
      session_configurations: TableDefinition<SessionConfiguration>;
      live_call_sessions: TableDefinition<LiveCallSession>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}


// =====================================================
// BILLING TYPES (Generated by Migration Agent)
// =====================================================

export type PlanTier = 'free' | 'individual' | 'pro' | 'team';

export type SubscriptionStatus =
  | 'active'
  | 'canceled'
  | 'past_due'
  | 'trialing'
  | 'incomplete'
  | 'incomplete_expired'
  | 'unpaid';

export interface Subscription {
  id: string;
  user_id: string;
  stripe_subscription_id: string | null;
  stripe_customer_id: string | null;
  plan_tier: PlanTier;
  status: SubscriptionStatus;
  current_period_start: string | null;
  current_period_end: string | null;
  cancel_at_period_end: boolean;
  canceled_at: string | null;
  trial_start: string | null;
  trial_end: string | null;
  created_at: string;
  updated_at: string;
}

export type FeatureType = 'live-call' | 'practice' | 'email' | 'analyzer';

export type EventType = 'api_call' | 'duration' | 'generation' | 'analysis';

export interface UsageEvent {
  id: string;
  user_id: string;
  feature: FeatureType;
  event_type: EventType;
  quantity: number;
  tokens_used: number | null;
  cost_usd: number | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface UsageLimit {
  id: string;
  plan_tier: PlanTier;
  monthly_live_call_minutes: number | null;
  monthly_practice_sessions: number | null;
  monthly_emails: number | null;
  monthly_analyses: number | null;
  features_enabled: Record<string, boolean>;
  created_at: string;
  updated_at: string;
}

export type InvoiceStatus = 'draft' | 'open' | 'paid' | 'void' | 'uncollectible';

export interface Invoice {
  id: string;
  user_id: string;
  stripe_invoice_id: string;
  stripe_subscription_id: string | null;
  amount_due: number;
  amount_paid: number;
  currency: string;
  status: InvoiceStatus;
  invoice_pdf: string | null;
  hosted_invoice_url: string | null;
  paid_at: string | null;
  due_date: string | null;
  created_at: string;
  updated_at: string;
}

// Helper type for checking usage limits
export interface UsageLimitCheck {
  feature: FeatureType;
  allowed: boolean;
  current_usage: number;
  limit: number | null; // null = unlimited
  remaining: number | null; // null = unlimited
}
