-- ============================================================================
-- Migration: 20260215000002_seed_methodology_fanatical_prospecting
-- Purpose: Seed Fanatical Prospecting methodology (Jeb Blount) with full
--          AI coaching content. Fills the prospecting gap — SAIL previously
--          had zero prospecting-focused methodologies.
--
-- Idempotent: uses ON CONFLICT (slug) DO NOTHING so re-running is safe.
-- ============================================================================

INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'Fanatical Prospecting', 'fanatical-prospecting', 'Jeb Blount',
  'Fill your pipeline relentlessly using a multi-channel, disciplined prospecting system.',
  'Fanatical Prospecting is the definitive system for keeping your sales pipeline full. Based on the premise that "the one who prospects the most wins," it provides structured frameworks for telephone calls, email outreach, in-person visits, social selling, and voicemail — all tied together with disciplined time-blocking and pipeline math. The methodology emphasizes that prospecting is the hardest part of sales and must be treated as a sacred, non-negotiable daily activity.',
  'Block your first hours for prospecting (Eat the Frog). Use the 5-Step Telephone Framework to reach decision makers efficiently. Handle Reflex Responses, Brush-Offs, and Objections with the 3-Step RBO Turnaround (Anchor → Disrupt → Ask). Layer channels using the Triple Threat (call + LinkedIn + email) to build familiarity. Organize prospects using the Prospecting Pyramid. Plan in-person visits with the Hub-and-Spoke system. Track your numbers religiously.',
  'Sales reps who need to build pipeline from scratch — especially cold outreach to dance studios, schools, daycares, and sports organizations where nobody is expecting your call.',
  '[{"title":"Jeb Blount - Fanatical Prospecting","url":"https://www.youtube.com/watch?v=NA5EBCNWyLY","description":"Author overview of the fanatical prospecting system"}]'::jsonb,
  '[{"title":"Fanatical Prospecting","author":"Jeb Blount","year":2015,"url":"https://www.amazon.com/Fanatical-Prospecting-Conversations-Appointments-Enterprise/dp/1119144752"}]'::jsonb,
  'phone', 'process', 5, 'intermediate',
  ARRAY['prospecting','cold-calling','pipeline','telephone','email','objection-handling','time-blocking','volume-photography','b2b'],

  -- system_prompt_template
  E'You are a sales coach specializing in Jeb Blount''s Fanatical Prospecting methodology, applied to volume photography B2B sales (picture days for dance studios, schools, daycares, sports orgs in the San Antonio area).\n\nCore belief: The number one reason for failure in sales is an empty pipeline — and the number one reason for an empty pipeline is the failure to prospect. Prospecting is non-negotiable.\n\nKey frameworks to coach:\n\n1. THE 5-STEP TELEPHONE FRAMEWORK:\n   - Get Attention (say their NAME)\n   - Identify Yourself (name + company, NO "how are you?")\n   - Tell Why ("the reason I''m calling is...")\n   - Bridge with Because (connect to THEIR problem)\n   - Ask + Shut Up (assumptive ask, then silence)\n   No pauses until you ask. 10 seconds or less to get to the point.\n\n2. THE 3-STEP RBO TURNAROUND (Anchor → Disrupt → Ask):\n   - Anchor: Simple statement to buy time ("That''s exactly why I called")\n   - Disrupt: Something unexpected that pulls them toward you, not pushes against them\n   - Ask: Confidently ask again for commitment\n   Never "overcome" objections — disrupt expectations. Judo principle: win without causing injury.\n\n3. TIME BLOCKING:\n   - Golden Hours = prime selling time (calls, meetings, demos)\n   - Platinum Hours = admin tasks (email, CRM, research)\n   - Eat the Frog: first 1-2 hours are sacred prospecting blocks\n   - Horstman''s Corollary: work contracts to fit the time allowed\n\n4. PIPELINE MATH:\n   - 30-Day Rule: prospecting today pays off in 90 days\n   - Law of Replacement: closing 1 deal removes ~10 prospects from pipeline\n   - Track: dials, contacts, appointments, close rate\n\n5. MULTI-CHANNEL:\n   - Triple Threat: voicemail + LinkedIn + email builds familiarity\n   - Balanced Prospecting: don''t rely on just one channel\n   - Law of Familiarity: more touches = more receptivity\n\n6. EMAIL FRAMEWORK (Hook → Relate → Bridge → Ask):\n   - Hook: compelling subject + opening about THEM\n   - Relate: show empathy for their situation\n   - Bridge: connect their problem to how you help (WIIFM)\n   - Ask: clear, direct request with specific time\n\nKey coaching rules:\n- Prospecting is interruption — be respectful but efficient\n- Never ask "How are you?" on cold calls\n- Assumptive language always ("How about Tuesday at 2?" not "Would you be interested?")\n- After 2 unsuccessful RBO turnarounds, graciously move on (NEXT)\n- Persistence always wins — the most valuable prospects are the hardest to reach',

  -- feature_prompt_overrides
  '{"practice_mode":"Role-play cold calls to dance studios and schools using the 5-Step Telephone Framework. Throw common RBOs (''we''re happy,'' ''not interested,'' ''send me info,'' ''I''m busy'') and score the user on their Anchor-Disrupt-Ask turnaround. Evaluate speed, assumptive language, and whether they shut up after asking.","live_call":"Detect when the rep is prospecting vs. discovery. Track 5-Step Framework compliance. Alert on: asking ''how are you,'' pausing too long, non-assumptive language, fighting objections instead of disrupting. Suggest specific RBO turnaround scripts when objections are detected.","call_analyzer":"Score the call on: time to ask (under 10 seconds?), RBO handling (did they anchor-disrupt-ask?), assumptive language ratio, question vs statement ratio, and whether they achieved their prospecting objective (appointment, info, or familiarity).","email_composer":"Draft prospecting emails using the Hook-Relate-Bridge-Ask framework. Subject lines under 50 characters, about the prospect not you. Use emotional words (flexibility, peace of mind, frustrated, stressed). Include a specific time ask."}'::jsonb,

  -- scoring_rubric
  '[{"key":"framework_execution","name":"5-Step Framework Execution","description":"Does the rep follow Get Attention → Identify → Tell Why → Bridge → Ask + Shut Up?","weight":0.25,"anchors":{"1":"No structure, rambling opener","3":"Partial framework, missing steps","5":"Clean 5-step execution under 10 seconds with assumptive ask"}},{"key":"rbo_handling","name":"RBO Turnaround Quality","description":"When objections hit, does the rep use Anchor → Disrupt → Ask?","weight":0.25,"anchors":{"1":"Accepts objection and gives up or argues","3":"Some turnaround attempt but incomplete","5":"Clean Anchor-Disrupt-Ask that pulls prospect toward you"}},{"key":"prospecting_discipline","name":"Prospecting Discipline","description":"Does the rep demonstrate disciplined, focused prospecting behavior?","weight":0.25,"anchors":{"1":"Unfocused, long-winded, wastes prospect time","3":"Mostly focused but some tangents","5":"Laser-focused, efficient, respects prospect time"}},{"key":"assumptive_language","name":"Assumptive Language","description":"Does the rep use confident, assumptive asks vs weak, permission-seeking language?","weight":0.25,"anchors":{"1":"Weak language: ''would you be interested,'' ''is this a good time''","3":"Mix of assumptive and weak","5":"Consistently assumptive: ''How about Tuesday at 2?'' with confidence"}}]'::jsonb,

  -- stages
  '[{"key":"preparation","name":"Preparation","order":1,"description":"Research the prospect, define your objective, organize your list using the Prospecting Pyramid.","signals":["Rep knows prospect name and basic business info","Has a clear objective for the call"],"transition_cues":["Prospect list is organized top-to-bottom","Objective is defined: appointment, info, close, or familiarity"],"coaching_tips":["Use the Prospecting Pyramid: hottest prospects first","Know your objective BEFORE you dial","Research takes 2 minutes — no excuses"]},{"key":"initial-contact","name":"Initial Contact","order":2,"description":"Execute the 5-Step Telephone Framework to reach the decision maker.","signals":["Rep uses prospect''s name first","Gets to the ask in under 10 seconds"],"transition_cues":["Prospect is listening and hasn''t hung up","Prospect responds to the ask"],"coaching_tips":["No ''how are you'' — go directly to their name","Bridge with THEIR problem, not your product","Ask assumptively and SHUT UP"]},{"key":"rbo-navigation","name":"RBO Navigation","order":3,"description":"Handle Reflex Responses, Brush-Offs, and Objections using Anchor-Disrupt-Ask.","signals":["Prospect gives an RBO","Rep stays calm and doesn''t argue"],"transition_cues":["Prospect softens after the disrupt","Prospect engages with a real conversation"],"coaching_tips":["Anchor buys you time — ''That''s exactly why I called''","Disrupt by agreeing or saying something unexpected","Ask again after the disrupt — confidently, with a specific time"]},{"key":"commitment","name":"Commitment","order":4,"description":"Secure the prospecting objective: appointment, information, or familiarity.","signals":["Prospect agrees to a meeting time","Prospect provides qualifying information","Prospect remembers you from a previous touch"],"transition_cues":["Objective is achieved — move to the next call","After 2 failed RBO turnarounds, graciously move on"],"coaching_tips":["If they say yes — confirm time, date, and next steps","If they say no after 2 turnarounds — say NEXT and move on","Log everything in CRM immediately"]}]'::jsonb,

  -- question_types
  '[{"key":"attention-name","name":"Attention by Name","description":"Open with their name to get immediate attention — the most beautiful word in any language.","purpose":"Break through distraction and get them to listen.","examples":["Hi Julie.","Hey Sarah."],"stage_affinity":["initial-contact"],"difficulty":"beginner"},{"key":"bridge-because","name":"Bridge with Because","description":"Connect your ask to a reason that matters to them. The word ''because'' triggers compliance.","purpose":"Give them a reason to give you what you want.","examples":["The reason I''m calling is because I work with several dance studios in your area and they''ve seen great results with professional picture-day partnerships.","I''m reaching out because I noticed your studio hosts 3 recitals a year and I thought you might benefit from a dedicated photography partner."],"stage_affinity":["initial-contact"],"difficulty":"beginner"},{"key":"assumptive-ask","name":"Assumptive Ask","description":"Ask for what you want with confidence, assuming you''ll get it. Include a specific day and time.","purpose":"Get a yes, no, or maybe — fast.","examples":["How about we meet Thursday at 2:00 PM?","I''d love to stop by Tuesday morning around 10:00. Does that work?"],"stage_affinity":["initial-contact","commitment"],"difficulty":"beginner"},{"key":"rbo-disrupt","name":"RBO Disrupt Question","description":"After anchoring, ask or say something unexpected that pulls them toward you instead of pushing.","purpose":"Break the prospect''s expected pattern and re-engage.","examples":["Most people say that before they see how much we can help — doesn''t it make sense to at least have a short meeting to find out?","If you''re happy, you should never change. I just want to get to know you — even if we never do business, I can give you a competitive benchmark."],"stage_affinity":["rbo-navigation"],"difficulty":"intermediate"},{"key":"qualifying","name":"Qualifying Questions","description":"Determine if this prospect is worth pursuing and at what level of the pyramid they belong.","purpose":"Prioritize your pipeline and define next objectives.","examples":["How many events do you host per year?","When is your next recital coming up?","Who typically makes the decision on photography vendors?"],"stage_affinity":["commitment"],"difficulty":"beginner"}]'::jsonb,

  -- vocabulary
  '{"RBO":"Reflex Response, Brush-Off, or Objection — the three types of pushback you get when prospecting.","Anchor":"A simple statement that holds you steady when an RBO hits, buying time for your logical brain to catch up.","Disrupt":"A statement or question that breaks the prospect''s expectation of a fight and pulls them toward you.","Golden Hours":"Prime selling time — only prospecting and customer engagement during these hours.","Platinum Hours":"Before/after Golden Hours — admin, CRM, research, proposals, email.","Eat the Frog":"Do the hardest thing first (prospecting) before anything else in the day.","Triple Threat":"Voicemail + LinkedIn + Email layered together to build familiarity before the next call.","Prospecting Pyramid":"Organize prospects from hottest (top) to coldest (bottom) and call from top down.","Law of Familiarity":"The more familiar a prospect is with you, the more likely they''ll engage. Every touch builds familiarity.","30-Day Rule":"The prospecting you do today pays off in the next 90 days. Miss today and you''ll feel it in 3 months.","Law of Replacement":"Closing 1 deal removes ~10 prospects from your pipeline, not just 1.","Hub-and-Spoke":"Plan in-person visits around preset appointments to maximize field time.","T-Call":"At every stop, look right, left, and behind — walk into those businesses too.","NEXT":"After a bad rejection, say this word and dial the next number immediately.","Assumptive language":"Asking for what you want with confidence, not permission-seeking."}'::jsonb,

  -- anti_patterns
  '[{"name":"Asking How Are You","description":"Opening a cold call with ''How are you?'' or any pleasantry that signals you''re a salesperson.","detection_signals":["Any form of how are you, how''s your day, hope I''m not catching you at a bad time","Pause after greeting before stating purpose"],"coaching_response":"Never ask how they are on a cold call. Say their name and go directly into ''The reason I''m calling is...'' — get to the point in 10 seconds."},{"name":"Fighting Objections","description":"Arguing with the prospect or trying to overcome their objection with logic.","detection_signals":["Saying ''but'' after an objection","Listing reasons they''re wrong","Getting defensive or frustrated"],"coaching_response":"Don''t fight — disrupt. Use the judo principle: pull them toward you. Try: ''That''s fantastic! All I want to do is get to know you a little better. How about Tuesday at 11?''"},{"name":"Non-Assumptive Language","description":"Using weak, permission-seeking language instead of confident, assumptive asks.","detection_signals":["Is this a good time?","Would you be interested?","I was wondering if...","What do you think?"],"coaching_response":"Replace with assumptive language: ''How about Thursday at 2?'' Your tone and words must project confidence. Prospects say yes 70% of the time when asked assumptively."},{"name":"Talking After Asking","description":"Continuing to talk after making an ask instead of shutting up and letting the prospect respond.","detection_signals":["Multiple sentences after the ask without a prospect response","Nervous filler words after the question","Offering an out or weakening the ask"],"coaching_response":"Ask and shut up. The silence feels unbearable but the prospect needs time to process. Most salespeople talk themselves OUT of yesses."},{"name":"Prospecting Avoidance","description":"Spending Golden Hours on non-prospecting activities like email, CRM updates, or research.","detection_signals":["Doing admin during prime calling time","Excessive pre-call research as procrastination","Checking email between every call"],"coaching_response":"Block your first 1-2 hours for prospecting. Golden Hours are for calling, not admin. Move CRM updates and email to Platinum Hours."}]'::jsonb,

  -- success_signals
  '[{"name":"Prospect Engages After RBO Turnaround","description":"After an initial brush-off, the prospect re-engages and starts a real conversation.","significance":"high"},{"name":"Prospect Agrees to Appointment","description":"The primary prospecting objective is achieved — a meeting is set.","significance":"high"},{"name":"Prospect Provides Qualifying Information","description":"Prospect shares details about their business, events, or decision-making process.","significance":"medium"},{"name":"Prospect Asks About Your Service","description":"Prospect initiates curiosity about what you offer — buying signal.","significance":"high"},{"name":"Prospect Remembers Previous Touch","description":"On a follow-up call, the prospect recognizes your name from a voicemail, email, or LinkedIn touch.","significance":"medium"},{"name":"Gatekeeper Transfers You","description":"The gatekeeper connects you to the decision maker without resistance.","significance":"medium"}]'::jsonb,

  -- learning_objectives
  '[{"title":"Master the 5-Step Telephone Prospecting Framework","level":"beginner"},{"title":"Handle RBOs with the Anchor-Disrupt-Ask turnaround","level":"beginner"},{"title":"Time-block Golden Hours for prospecting and protect them","level":"beginner"},{"title":"Use assumptive language for every ask","level":"beginner"},{"title":"Build multi-channel familiarity with the Triple Threat","level":"intermediate"},{"title":"Organize prospects using the Prospecting Pyramid","level":"intermediate"},{"title":"Craft emails using the Hook-Relate-Bridge-Ask framework","level":"intermediate"},{"title":"Track prospecting numbers and understand pipeline math","level":"intermediate"},{"title":"Navigate gatekeepers using the 7 Keys strategy","level":"advanced"},{"title":"Plan in-person prospecting with the Hub-and-Spoke system","level":"advanced"}]'::jsonb,

  -- concept_chunks
  '[{"title":"The Pipeline Is Everything","summary":"The number one reason for sales failure is an empty pipeline. The number one reason for an empty pipeline is failure to prospect. Prospecting is non-negotiable — it must happen every single day, no matter what.","key_takeaway":"Eat the Frog: make prospecting your first activity every day."},{"title":"The 5-Step Framework","summary":"Get Attention (their name) → Identify (your name + company) → Tell Why (the reason I''m calling) → Bridge with Because (connect to their problem) → Ask + Shut Up (assumptive ask, then silence). All in under 10 seconds.","key_takeaway":"No pauses until you ask. Speed and directness show respect for their time."},{"title":"Anchor-Disrupt-Ask","summary":"When you get an RBO, don''t fight. Anchor with a simple statement to buy time, Disrupt with something unexpected that pulls them toward you, then Ask again. After 2 failed turnarounds, say NEXT and move on.","key_takeaway":"You cannot argue someone into believing they''re wrong. Disrupt their expectations instead."},{"title":"The Law of Familiarity","summary":"The more familiar a prospect is with you, the more likely they are to engage. Layer voicemail + LinkedIn + email to build familiarity before your next call. Cold prospects need 20-50 touches; familiar prospects need 1-10.","key_takeaway":"Every touch builds familiarity — even unanswered calls and unopened emails contribute."},{"title":"Pipeline Math","summary":"The 30-Day Rule: today''s prospecting pays off in 90 days. The Law of Replacement: closing 1 deal removes ~10 prospects. You must replace at a rate that exceeds your closing ratio or your pipeline will dry up.","key_takeaway":"Consistency beats intensity. A steady daily cadence always outperforms sporadic bursts."}]'::jsonb,

  'pro',
  'Fanatical Prospecting is a methodology developed by Jeb Blount of Sales Gravy. Used for educational reference.',
  'FP, Blount Method', 14, true
) ON CONFLICT (slug) DO NOTHING;
