-- ============================================================================
-- Migration: 20260215000003_seed_methodology_hormozi_closing
-- Purpose: Seed Hormozi Closing Method (Alex Hormozi) with full AI coaching
--          content. Covers objection reframing and closing mechanics.
--
-- Idempotent: uses ON CONFLICT (slug) DO NOTHING so re-running is safe.
-- ============================================================================

INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'Hormozi Closing Method', 'hormozi-closing-method', 'Alex Hormozi',
  'Reframe objections and close with empathy using the 3A Framework.',
  'Alex Hormozi''s closing methodology, refined from 4,000+ sales closes, focuses on objection reframing rather than objection overcoming. The core insight: you cannot win a sale by winning an argument. Instead, you Acknowledge what they said, Associate their behavior with successful customers, then Ask a question that keeps you in control. Combined with the "Be Like Smoke" principle (never disagree, always ask questions) and Straw Man techniques for delivering tough truths, this methodology turns objection handling from a fight into a dance.',
  'When any objection or stall occurs, apply the 3A Framework: Acknowledge (repeat what they said back), Associate (connect their concern to successful customers), Ask (reframe with a question). Use Straw Man stories to deliver tough truths without insulting the prospect. Maintain childlike curiosity — respond with genuine wonder ("Huh, that''s interesting") instead of defensiveness. Use escalating directness: "What''s your main concern?" → "What are you afraid of?" → "What would make this a no?" → "What would it take to say yes?"',
  'Reps who are good at prospecting and discovery but struggle to close — especially when prospects stall with "I need to think about it," "need to talk to my partner," or "not the right time."',
  '[{"title":"Alex Hormozi - After Closing 4000+ Sales","url":"https://www.youtube.com/watch?v=RVbvhPGFi6E","description":"Full breakdown of the reframing and closing methodology"}]'::jsonb,
  '[{"title":"$100M Offers","author":"Alex Hormozi","year":2021,"url":"https://www.amazon.com/100M-Offers-People-Stupid-Saying/dp/1737475731"},{"title":"$100M Leads","author":"Alex Hormozi","year":2023,"url":"https://www.amazon.com/100M-Leads-Strangers-Want-Stuff/dp/1737475766"}]'::jsonb,
  'message-circle', 'framework', 4, 'intermediate',
  ARRAY['closing','objection-handling','reframing','influence','empathy','volume-photography','b2b'],

  -- system_prompt_template
  E'You are a sales coach specializing in Alex Hormozi''s Closing Method, applied to volume photography B2B sales (picture days for dance studios, schools, daycares, sports orgs).\n\nCore principle: You don''t close sales by being right — you close sales by making the prospect right. It''s a dance, not a fight. It''s seduction, not force.\n\nKey frameworks to coach:\n\n1. THE 3A REFRAMING FRAMEWORK (Acknowledge → Associate → Ask):\n   After ANY objection or statement that isn''t "yes":\n   - ACKNOWLEDGE: Say what they said back to them. Builds rapport, shows listening, buys thinking time.\n   - ASSOCIATE: Connect their question/behavior to successful customers. "That''s actually what our most successful clients ask because they take this seriously."\n   - ASK: Ask a question that reframes the conversation and keeps you in control.\n\n2. BE LIKE SMOKE:\n   Never voice disagreement. You can''t catch smoke because it always side-shifts. Whatever they say, respond with a question — never a counter-argument. The person asking questions controls the conversation.\n\n3. STRAW MAN TECHNIQUE:\n   When you need to deliver a tough truth, use a third-party story: "I had someone earlier today in a similar situation..." This lets you say hard things without insulting the prospect directly.\n\n4. DEEP ASSOCIATION (The Label Effect):\n   Give the prospect a positive label ("you''re clearly a smart decision-maker") — they feel compelled to live up to it. Three types:\n   - "Earlier Today" — reference someone with the same concern\n   - "Successful Customer" — pair their concern with a success story\n   - "Appeal to Authority" — reference an expert or leader\n\n5. ESCALATING DIRECTNESS:\n   - First objection: "What''s your main concern?"\n   - Mid-sale stall: "What are you afraid of?"\n   - Late-stage stall: "What would make this a no?"\n   - Final close: "What would it take for you to say yes?"\n\n6. CHILDLIKE CURIOSITY ("Huh?" Technique):\n   Respond to hostility with genuine wonder. Say "huh" before your next statement. Seek to understand, not to win. Sticky note above your screen: "Keep the human #1."\n\nKey coaching rules:\n- A prospect believes almost nothing you say and almost everything THEY say\n- The goal is to ask questions so THEY conclude they''re a good fit\n- If someone pushes back on your questions, use the Mechanic Analogy: "It would be unethical for me to answer without looking under the hood first"\n- Never ask "Do you have any questions?" — that invites them to take control\n- The most productive salespeople make the most asks — but only because they use 3A so rapport is preserved\n- Frame yourself as a guide sharing information, not a closer trying to win',

  -- feature_prompt_overrides
  '{"practice_mode":"Role-play closing scenarios where the prospect gives common stalls: ''I need to think about it,'' ''need to talk to my partner,'' ''not the right time,'' ''too expensive.'' Score on 3A Framework execution, smoke technique (never disagree), and escalating directness. Throw increasingly resistant prospects to test resilience.","live_call":"Detect when an objection or stall is happening. Suggest the 3A reframe in real-time: what to acknowledge, how to associate, what question to ask. Flag when the rep argues, disagrees, or uses ''but.'' Track the escalating directness ladder.","call_analyzer":"Score the call on: number of asks made, rapport maintenance throughout, 3A framework usage per objection, whether the rep argued or used smoke, and escalating directness progression. Highlight moments where a straw man would have helped.","email_composer":"Draft follow-up emails that use the 3A framework in written form. Acknowledge their concern, associate them with successful clients, and ask a question that reopens the conversation. Use straw man stories when appropriate."}'::jsonb,

  -- scoring_rubric
  '[{"key":"three_a_execution","name":"3A Framework Execution","description":"Does the rep Acknowledge, Associate, and Ask when handling objections?","weight":0.30,"anchors":{"1":"Argues with objections or gives up immediately","3":"Some acknowledgment but skips association or asks weak questions","5":"Clean 3A on every objection — acknowledges, associates with success, asks a reframing question"}},{"key":"smoke_technique","name":"Be Like Smoke","description":"Does the rep avoid disagreement and redirect with questions instead?","weight":0.25,"anchors":{"1":"Directly disagrees or argues with the prospect","3":"Mostly avoids conflict but occasionally pushes back","5":"Never disagrees — always side-shifts with curiosity and questions"}},{"key":"rapport_preservation","name":"Rapport Preservation","description":"Does rapport stay intact or improve throughout the close, even with multiple asks?","weight":0.25,"anchors":{"1":"Rapport breaks down — prospect sounds annoyed or defensive","3":"Rapport is neutral — not damaged but not built","5":"Rapport strengthens with each exchange — prospect feels heard and validated"}},{"key":"closing_courage","name":"Closing Courage","description":"Does the rep make multiple asks and escalate directness when needed?","weight":0.20,"anchors":{"1":"Only asks once and accepts the stall","3":"Makes 2-3 asks but doesn''t escalate","5":"Makes multiple asks with escalating directness while maintaining rapport"}}]'::jsonb,

  -- stages
  '[{"key":"rapport-frame","name":"Rapport Frame","order":1,"description":"Establish the frame of guide/advisor, not closer/seller. Use curiosity-based engagement.","signals":["Prospect is relaxed and talking freely","Prospect shares concerns openly"],"transition_cues":["Trust is established","Prospect is comfortable enough to raise objections"],"coaching_tips":["Frame yourself as someone sharing information to help them make a good decision","Use the time-travel thought experiment: sell with the empathy of someone who knows the future","Sticky note: Keep the human #1"]},{"key":"objection-reframe","name":"Objection Reframe","order":2,"description":"Apply the 3A Framework to every objection and stall. Be like smoke — never fight.","signals":["Prospect raises a concern or stall","Rep stays calm and curious"],"transition_cues":["Prospect softens after the reframe","New, deeper concern is revealed"],"coaching_tips":["Acknowledge first — always. Never skip this step.","Associate: ''That actually makes you just like [successful client] who had the same concern''","Ask: keep control by asking a question, never by making a statement"]},{"key":"deep-discovery","name":"Deep Discovery","order":3,"description":"Use escalating directness to get to the real concern behind the surface objection.","signals":["Prospect reveals their true fear or hesitation","Surface objections peel away to reveal the real blocker"],"transition_cues":["You''ve identified the real concern","Prospect says something like ''honestly, my main worry is...''"],"coaching_tips":["Escalate: main concern → what are you afraid of → what would make this a no","Use straw men to deliver tough truths through third-party stories","If they say ''I need to think about it,'' ask: ''What are the main variables in your decision?''"]},{"key":"commitment-close","name":"Commitment Close","order":4,"description":"Once the real concern is addressed, use an assumptive close that positions you as the guide.","signals":["Prospect''s concerns are resolved","Prospect is nodding or verbally agreeing"],"transition_cues":["All concerns have been addressed","Prospect asks about next steps or logistics"],"coaching_tips":["''At the end of the day, you want to make a good decision. I''m the source of your information. The best decision we can make is here together.''","Only say this after maintaining rapport with 3A throughout","Ask: ''What would it take for us to take the next step together?''"]}]'::jsonb,

  -- question_types
  '[{"key":"acknowledge-reflect","name":"Acknowledge & Reflect","description":"Repeat what the prospect said back to them to show active listening and buy thinking time.","purpose":"Build rapport and show you heard them before responding.","examples":["So you want to make sure you''re getting the best value — totally get it.","You''re saying timing is the main concern — I understand that."],"stage_affinity":["objection-reframe"],"difficulty":"beginner"},{"key":"association","name":"Association Question","description":"Connect the prospect''s behavior to successful customers to pull them back toward buying.","purpose":"Reframe their concern as a sign of being a good fit, not a reason to leave.","examples":["That actually makes you just like several of our best studio partners who asked the same question. Can I share what happened with them?","Our most successful clients are the ones who take this kind of careful approach."],"stage_affinity":["objection-reframe"],"difficulty":"intermediate"},{"key":"escalating-direct","name":"Escalating Directness","description":"Progressively more direct questions that get to the real concern behind surface objections.","purpose":"Cut through vague stalls to reach the real blocker.","examples":["What are the main variables you''re using to make this decision?","What are you most afraid of having happen?","What would make this a no?","What would it take for you to say yes?"],"stage_affinity":["deep-discovery"],"difficulty":"intermediate"},{"key":"straw-man-setup","name":"Straw Man Setup","description":"Introduce a third-party story to deliver a tough truth without directly challenging the prospect.","purpose":"Say what needs to be said without damaging rapport.","examples":["I had someone earlier today in a similar situation. Can I share what we realized together?","That reminds me of a studio owner we worked with who had the exact same concern. Want to hear how it played out?"],"stage_affinity":["deep-discovery","commitment-close"],"difficulty":"advanced"},{"key":"self-close","name":"Self-Close Question","description":"Ask a question that leads the prospect to close themselves by articulating why they should buy.","purpose":"The prospect believes everything they say — get them to say yes.","examples":["Based on everything we''ve discussed, does it make sense to move forward?","You said your biggest frustration is [X] — what happens if nothing changes?"],"stage_affinity":["commitment-close"],"difficulty":"advanced"}]'::jsonb,

  -- vocabulary
  '{"3A Framework":"Acknowledge → Associate → Ask. The core objection reframing structure.","Be Like Smoke":"Never disagree — always side-shift with a question, like smoke you can''t grab.","Straw Man":"A third-party story used to deliver tough truths without insulting the prospect directly.","Deep Association":"Connecting the prospect''s concern to successful customers, an authority figure, or a recent similar conversation.","Label Effect":"Giving the prospect a positive label they feel compelled to live up to.","Escalating Directness":"A ladder of increasingly direct questions: concern → afraid of → would make it a no → would it take to say yes.","Mechanic Analogy":"When pressed for answers: ''It would be unethical to diagnose without looking under the hood first.''","Childlike Curiosity":"Responding to hostility with genuine wonder instead of defensiveness.","The Guide Frame":"Positioning yourself as someone sharing information, not a closer trying to win.","Commission Breath":"When prospects can smell that you just want the money — the opposite of genuine care."}'::jsonb,

  -- anti_patterns
  '[{"name":"Arguing With Objections","description":"Directly disagreeing with or countering a prospect''s objection.","detection_signals":["Using ''but'' after an objection","Listing reasons the prospect is wrong","Getting defensive or raising voice"],"coaching_response":"Be like smoke. Never disagree. Acknowledge what they said, associate their concern with successful customers, then ask a question. You can''t win a sale by winning an argument."},{"name":"Skipping Acknowledgment","description":"Jumping straight to your counter-point without acknowledging what the prospect said.","detection_signals":["Responding to an objection with immediate pitch","Not reflecting the prospect''s words back","Prospect feels unheard"],"coaching_response":"Always acknowledge first. Say their concern back to them: ''So you''re saying [X] — I totally get that.'' This single step preserves rapport for everything that follows."},{"name":"Answering Blind Questions","description":"Guessing at what the prospect is really asking instead of asking clarifying questions.","detection_signals":["Long answer to a vague question","Prospect looks confused after your response","You assumed what they meant"],"coaching_response":"When you don''t know the right answer, ask more questions about their question. ''Tell me specifically what you''re looking for'' is always safe."},{"name":"Single Ask Then Quit","description":"Only asking for the sale once and accepting the first stall.","detection_signals":["Prospect stalls and rep says okay","No follow-up question after ''I need to think about it''","Rep ends call after first no"],"coaching_response":"The most productive salespeople make the most asks. Use 3A to maintain rapport, then escalate: ''What are the main variables in your decision?'' You can ask as many times as you want without losing rapport if you acknowledge every time."},{"name":"Asking Do You Have Questions","description":"Inviting the prospect to surface objections by asking if they have questions.","detection_signals":["Any form of ''do you have any questions?'' or ''what questions do you have?''"],"coaching_response":"Never ask this — you''re literally inviting them to take control and raise objections. Instead, continue guiding the conversation with your own questions."}]'::jsonb,

  -- success_signals
  '[{"name":"Prospect Reveals True Concern","description":"After 3A reframing, the prospect shares their real fear or hesitation instead of surface stalls.","significance":"high"},{"name":"Prospect Self-Closes","description":"Prospect articulates why they should move forward without being told.","significance":"high"},{"name":"Prospect Asks About Next Steps","description":"Prospect initiates logistics: ''So what happens next?'' or ''How do we get started?''","significance":"high"},{"name":"Prospect Lives Up to Label","description":"After being labeled positively, the prospect''s behavior aligns with that label.","significance":"medium"},{"name":"Rapport Strengthens Through Objections","description":"Despite multiple objections and asks, the prospect becomes more engaged and friendly.","significance":"high"},{"name":"Straw Man Lands","description":"Prospect says ''that makes sense'' or ''I see what you mean'' after a third-party story.","significance":"medium"}]'::jsonb,

  -- learning_objectives
  '[{"title":"Master the 3A Framework (Acknowledge, Associate, Ask)","level":"beginner"},{"title":"Learn to Be Like Smoke — never disagree, always redirect with questions","level":"beginner"},{"title":"Use escalating directness to find the real concern behind surface stalls","level":"intermediate"},{"title":"Deploy Straw Man stories to deliver tough truths without damaging rapport","level":"intermediate"},{"title":"Apply the Label Effect to influence prospect behavior","level":"intermediate"},{"title":"Make multiple asks while maintaining and strengthening rapport","level":"advanced"},{"title":"Use the Mechanic Analogy when pressed for premature answers","level":"advanced"},{"title":"Master childlike curiosity under pressure — respond with wonder, not defense","level":"advanced"}]'::jsonb,

  -- concept_chunks
  '[{"title":"The 3A Reframe","summary":"When you hear anything but yes: Acknowledge (say it back), Associate (connect to successful customers), Ask (reframe with a question). This lets you make unlimited asks without losing rapport because you validate the prospect at every turn.","key_takeaway":"The 3A reframe is the bridge between hearing an objection and delivering your close. Without it, closes sound combative."},{"title":"Be Like Smoke","summary":"You can''t catch smoke because it always side-shifts. Whatever the prospect says, you respond with a question — never a counter-argument. A prospect believes almost nothing you say and almost everything they say. The goal is to ask questions so they conclude they''re a good fit.","key_takeaway":"Close sales by making the prospect right, not by being right yourself."},{"title":"Straw Man for Tough Truths","summary":"Sometimes you need to say something hard — like ''it''s not a time problem, it''s a priorities problem.'' Saying it directly risks rapport. A straw man (''I had someone earlier today...'') creates a neutral third party you can speak through.","key_takeaway":"Use ''Earlier Today,'' ''Successful Customer,'' or ''Appeal to Authority'' to say almost anything without offending."},{"title":"Escalating Directness","summary":"Start soft (''What''s your main concern?'') and escalate (''What are you afraid of?'' → ''What would make this a no?'' → ''What would it take to say yes?''). Each level cuts closer to the real issue. Only works after rapport is built.","key_takeaway":"The bold ask ''What are you afraid of?'' cuts through all the noise — but only when trust is already established."},{"title":"The Guide Frame","summary":"You''re not a closer trying to win — you''re a guide sharing information to help them make a good decision. Hormozi''s time-travel thought experiment: imagine selling to your past self with absolute empathy and patience. That''s the energy every sales conversation needs.","key_takeaway":"Frame: ''I''m going to share information that helps you make a good decision. The best decision we can make is here together.''"} ]'::jsonb,

  'pro',
  'This methodology is based on publicly available teachings by Alex Hormozi. Used for educational reference.',
  'Hormozi Method, 3A Framework', 15, true
) ON CONFLICT (slug) DO NOTHING;
