-- ============================================================================
-- Migration: 20260214000007_seed_methodologies_part1
-- Purpose: Seed the first 4 sales methodologies with full AI coaching content.
--
-- Methodologies seeded:
--   1. Questions That Sell (Paul Cherry)   — free, beginner
--   2. SPIN Selling (Neil Rackham)         — free, intermediate
--   3. Consultative Selling (Mack Hanan)   — free, intermediate
--   4. Gap Selling (Keenan)                — pro,  intermediate
--
-- Idempotent: uses ON CONFLICT (slug) DO NOTHING so re-running is safe.
-- ============================================================================

-- 1. Questions That Sell — Paul Cherry
INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'Questions That Sell', 'questions-that-sell', 'Paul Cherry',
  'Master the art of asking questions that move prospects from curiosity to commitment.',
  'Paul Cherry''s methodology focuses on asking the right questions at the right time. Questions are the salesperson''s most powerful tool — they uncover needs, build trust, and guide prospects through a commitment journey from "Sure" (open but uncommitted) through "Want To" (sees the value) to "Have To" (feels urgency to act).',
  'Guide the conversation through three commitment stages using targeted question types. Start with lock-on questions to build rapport, use expansion and impact questions to uncover deep needs, then comparison and vision questions to create urgency.',
  'Volume photography B2B sales reps who need to book more picture-day partnerships with dance studios, schools, and sports organizations.',
  '[{"title":"Paul Cherry - Questions That Sell","url":"https://www.youtube.com/watch?v=Rs0qaXf4wKc","description":"Author overview of the questioning methodology"}]'::jsonb,
  '[{"title":"Questions That Sell","author":"Paul Cherry","year":2017,"url":"https://www.amazon.com/Questions-That-Sell-Powerful-Discovery/dp/0814438709"}]'::jsonb,
  'help-circle', 'questioning', 5, 'beginner',
  ARRAY['questioning','discovery','rapport','commitment','volume-photography','b2b'],
  E'You are a sales coach specializing in Paul Cherry''s "Questions That Sell" methodology, applied to volume photography B2B sales (picture days for dance studios, schools, daycares, sports orgs in the San Antonio area).\n\nThe three commitment stages are:\n1. SURE — Prospect is polite but uncommitted. Use lock-on and expansion questions to build rapport and learn about their current photography situation.\n2. WANT TO — Prospect sees potential value. Use impact and comparison questions to deepen need awareness ("What happens when parents can''t buy quality photos?" or "How does your current photographer handle online galleries?").\n3. HAVE TO — Prospect feels urgency. Use vision questions to paint the future state ("Imagine parents raving about the photo experience at your next recital — how would that affect enrollment?").\n\nKey principles:\n- Never pitch before asking. Questions come first.\n- Listen for emotional language — it signals stage transitions.\n- Match question complexity to the prospect''s engagement level.\n- Always connect back to the prospect''s business outcomes (enrollment, parent satisfaction, revenue).',
  '{"practice_mode":"Focus on role-playing common volume photography sales scenarios: cold calls to dance studio owners, follow-ups after events, handling objections about switching photographers. Score the user on question quality and stage progression.","live_call":"Detect the current commitment stage from conversation context. Suggest the next best question type. Flag when the rep is pitching instead of asking.","call_analyzer":"Score the call on question-to-statement ratio, stage progression, and whether the rep reached the Have To stage. Highlight missed opportunities to ask deeper questions.","email_composer":"Draft outreach emails that use curiosity-provoking questions as subject lines and openers, following Cherry''s principle that questions engage more than statements."}'::jsonb,
  '[{"key":"question_quality","name":"Question Quality","description":"Are questions open-ended, specific, and relevant to the prospect''s business?","weight":0.25,"anchors":{"1":"Closed or generic questions only","3":"Mix of open and closed, somewhat relevant","5":"Consistently open-ended, specific, and business-relevant"}},{"key":"stage_progression","name":"Stage Progression","description":"Does the conversation move naturally through Sure → Want To → Have To?","weight":0.30,"anchors":{"1":"Stuck in one stage or skipped stages","3":"Some progression but uneven","5":"Smooth natural progression through all stages"}},{"key":"rapport_building","name":"Rapport Building","description":"Does the rep build genuine connection through active listening and lock-on questions?","weight":0.20,"anchors":{"1":"No rapport attempts","3":"Some rapport but formulaic","5":"Genuine connection with follow-up on prospect responses"}},{"key":"need_discovery","name":"Need Discovery","description":"Are the prospect''s real needs uncovered through expansion and impact questions?","weight":0.25,"anchors":{"1":"Needs never explored","3":"Surface needs identified","5":"Deep business and emotional needs uncovered"}}]'::jsonb,
  '[{"key":"sure","name":"Sure","order":1,"description":"Prospect is open but uncommitted — polite interest only.","signals":["Short answers","Polite but non-committal language","No questions back"],"transition_cues":["Prospect shares a specific pain point","Mentions a past negative experience","Asks a clarifying question about your service"],"coaching_tips":["Use lock-on questions to build rapport","Mirror their language","Don''t pitch yet — keep asking"]},{"key":"want-to","name":"Want To","order":2,"description":"Prospect sees value and is actively engaged in the conversation.","signals":["Longer answers with detail","Sharing internal challenges","Asking about capabilities"],"transition_cues":["Prospect quantifies a problem","Expresses frustration with status quo","Asks about pricing or timeline"],"coaching_tips":["Deepen with impact questions","Explore consequences of inaction","Connect their pain to your solution without pitching"]},{"key":"have-to","name":"Have To","order":3,"description":"Prospect feels urgency and is ready to move forward.","signals":["Future-oriented language","Asking next steps","Involving other decision makers"],"transition_cues":["Asks for a proposal","Sets a meeting","Commits to a timeline"],"coaching_tips":["Use vision questions to reinforce the future state","Summarize the value in their words","Offer a clear next step"]}]'::jsonb,
  '[{"key":"lock-on","name":"Lock-On Questions","description":"Build on something the prospect just said to show active listening.","purpose":"Build rapport and demonstrate you''re paying attention.","examples":["You mentioned parents complained last year — what specifically upset them?","You said enrollment is your top priority — how does the photo experience factor in?"],"stage_affinity":["sure"],"difficulty":"beginner"},{"key":"impact","name":"Impact Questions","description":"Explore the consequences of the prospect''s current situation.","purpose":"Help the prospect feel the weight of their problem.","examples":["What happens to parent satisfaction when photo quality is inconsistent?","How does a bad picture-day experience affect your studio''s reputation?"],"stage_affinity":["want-to"],"difficulty":"intermediate"},{"key":"expansion","name":"Expansion Questions","description":"Broaden the conversation to uncover related needs.","purpose":"Discover needs the prospect hasn''t considered.","examples":["Beyond photos, what other parts of recital day create stress for your staff?","How do your families currently share and purchase event photos?"],"stage_affinity":["sure","want-to"],"difficulty":"beginner"},{"key":"comparison","name":"Comparison Questions","description":"Contrast current state with alternatives or past experiences.","purpose":"Create a benchmark that highlights gaps.","examples":["How does your current photographer compare to what you''d ideally want?","What changed between this year and when picture day ran smoothly?"],"stage_affinity":["want-to"],"difficulty":"intermediate"},{"key":"vision","name":"Vision Questions","description":"Paint a picture of the desired future state.","purpose":"Create emotional urgency by making the solution feel real.","examples":["Imagine parents getting a beautiful online gallery the same week as the recital — what would that mean for your studio?","If picture day were completely hassle-free, how would that change your event planning?"],"stage_affinity":["have-to"],"difficulty":"advanced"}]'::jsonb,
  '{"lock-on question":"A question that references something the prospect just said, showing active listening.","expansion question":"A question that broadens the topic to uncover related or hidden needs.","impact question":"A question exploring consequences of the current situation.","comparison question":"A question that contrasts the current state with an ideal or past state.","vision question":"A question that paints a picture of the desired future outcome.","Sure stage":"First commitment level — prospect is polite but not engaged.","Want To stage":"Second commitment level — prospect sees value and is curious.","Have To stage":"Third commitment level — prospect feels urgency to act."}'::jsonb,
  '[{"name":"Premature Pitching","description":"Jumping into product features before asking enough questions.","detection_signals":["Multiple consecutive statements without questions","Feature-dumping before understanding needs"],"coaching_response":"Pause — you''re pitching before discovering. Ask an expansion question about their current situation."},{"name":"Closed Question Chains","description":"Asking a series of yes/no questions that feel like an interrogation.","detection_signals":["Three or more closed questions in a row","Prospect giving one-word answers"],"coaching_response":"Switch to an open-ended lock-on question based on their last answer."},{"name":"Stage Skipping","description":"Jumping from Sure directly to Have To without building Want To.","detection_signals":["Urgency language before the prospect has expressed interest","Asking for the meeting before establishing value"],"coaching_response":"Slow down. The prospect isn''t there yet. Ask an impact question to deepen their engagement."}]'::jsonb,
  '[{"name":"Prospect Shares Unprompted Detail","description":"Prospect volunteers information without being asked — indicates trust and engagement.","significance":"high"},{"name":"Prospect Asks About Your Service","description":"Prospect initiates questions about what you offer — signals Want To stage.","significance":"high"},{"name":"Prospect Mentions Other Stakeholders","description":"Involving a co-owner or director means they''re thinking seriously.","significance":"medium"},{"name":"Emotional Language","description":"Words like frustrated, excited, worried signal deep engagement.","significance":"high"}]'::jsonb,
  '[{"title":"Understand the three commitment stages (Sure, Want To, Have To)","level":"beginner"},{"title":"Master the five question types and when to use each","level":"beginner"},{"title":"Recognize stage transition signals in live conversation","level":"intermediate"},{"title":"Avoid premature pitching and closed-question chains","level":"beginner"},{"title":"Apply vision questions to create urgency in volume photography sales","level":"advanced"}]'::jsonb,
  '[{"title":"The Sure → Want To → Have To Framework","summary":"Prospects move through three stages of commitment. Your job is to guide them with questions, not push them with pitches.","key_takeaway":"Match your question type to the prospect''s current stage."},{"title":"Lock-On Questions: The Rapport Builder","summary":"Reference what the prospect just said to show you''re listening. This builds trust fast.","key_takeaway":"Always start responses with a lock-on before introducing new topics."},{"title":"Vision Questions: Creating Urgency","summary":"Paint a vivid picture of the ideal future state so the prospect feels compelled to act.","key_takeaway":"Use vision questions only after the prospect has expressed a clear need."}]'::jsonb,
  'free', 'Questions That Sell is a methodology developed by Paul Cherry of Performance Based Results. Used for educational reference.',
  'QTS', 1, true
) ON CONFLICT (slug) DO NOTHING;

-- 2. SPIN Selling — Neil Rackham
INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'SPIN Selling', 'spin-selling', 'Neil Rackham',
  'Uncover implicit needs and develop them into explicit needs using four types of questions.',
  'SPIN Selling is based on research of 35,000+ sales calls. It replaces traditional closing techniques with a structured questioning approach: Situation questions (gather facts), Problem questions (uncover difficulties), Implication questions (develop the seriousness), and Need-Payoff questions (get the buyer to tell you the benefits).',
  'Progress through four question types in order: gather Situation facts, identify Problems, explore Implications of those problems, then let the buyer articulate Need-Payoff benefits. The key insight is that Implication and Need-Payoff questions correlate most with success.',
  'Reps selling higher-value photography packages or multi-event contracts where the buying decision involves more stakeholders.',
  '[{"title":"SPIN Selling Explained","url":"https://www.youtube.com/watch?v=F4Zu5ZZAG7I","description":"Overview of the SPIN framework"}]'::jsonb,
  '[{"title":"SPIN Selling","author":"Neil Rackham","year":1988,"url":"https://www.amazon.com/SPIN-Selling-Neil-Rackham/dp/0070511136"}]'::jsonb,
  'target', 'questioning', 5, 'intermediate',
  ARRAY['questioning','needs-analysis','research-backed','enterprise','volume-photography'],
  E'You are a sales coach specializing in Neil Rackham''s SPIN Selling methodology, applied to volume photography B2B sales (picture days for dance studios, schools, daycares, sports orgs).\n\nThe four question types in order:\n1. SITUATION — Gather factual background: "How many events per year do you host?" "Who handles photography currently?"\n2. PROBLEM — Uncover difficulties: "What challenges do you face with your current photographer?" "Are parents satisfied with photo quality?"\n3. IMPLICATION — Develop seriousness: "When parents are unhappy with photos, how does that affect word-of-mouth for your studio?" "What''s the cost of running picture day in-house?"\n4. NEED-PAYOFF — Buyer states benefits: "If you had a photographer who handled everything and delivered same-week galleries, how would that help?" "Would hassle-free picture days free up your staff for other priorities?"\n\nKey coaching principles:\n- Situation questions are necessary but low-value — keep them brief.\n- Problem questions are where the sale really starts.\n- Implication questions are the most powerful — they make small problems feel urgent.\n- Need-Payoff questions get the buyer to sell themselves on the solution.\n- In volume photography: connect implications to enrollment, parent satisfaction, staff burden, and revenue.',
  '{"practice_mode":"Role-play photography sales calls emphasizing the SPIN sequence. Evaluate whether the user progresses through all four types. Penalize excessive Situation questions.","live_call":"Track which SPIN type is being used. Alert when too many Situation questions are asked. Suggest Implication questions when problems are identified but not developed.","call_analyzer":"Map each question in the transcript to a SPIN type. Calculate the ratio of Implication+Need-Payoff to Situation+Problem. Higher ratios correlate with success.","email_composer":"Use Problem and Implication framing in outreach emails to make the prospect think about their current challenges before offering a solution."}'::jsonb,
  '[{"key":"question_progression","name":"SPIN Progression","description":"Does the rep follow the S→P→I→N sequence naturally?","weight":0.30,"anchors":{"1":"Random question types with no progression","3":"Partial sequence, some types missing","5":"Clean progression through all four types"}},{"key":"need_development","name":"Need Development","description":"Are implicit needs developed into explicit needs?","weight":0.25,"anchors":{"1":"Needs mentioned but never developed","3":"Some development but surface level","5":"Implicit needs fully developed into explicit, urgent needs"}},{"key":"implication_depth","name":"Implication Depth","description":"Do Implication questions make problems feel serious and urgent?","weight":0.25,"anchors":{"1":"No implication questions asked","3":"Generic implications","5":"Specific, business-quantified implications that create urgency"}},{"key":"buyer_commitment","name":"Buyer Commitment","description":"Does the buyer articulate the value themselves via Need-Payoff responses?","weight":0.20,"anchors":{"1":"Buyer passive throughout","3":"Buyer agrees but doesn''t elaborate","5":"Buyer enthusiastically describes how the solution would help"}}]'::jsonb,
  '[{"key":"situation","name":"Situation","order":1,"description":"Gather facts about the prospect''s current state.","signals":["Factual answers","Short, informational responses"],"transition_cues":["You have enough context to identify a problem","Prospect mentions a difficulty unprompted"],"coaching_tips":["Keep Situation questions to a minimum — 2 to 3 max","Use research to pre-answer Situation questions before the call"]},{"key":"problem","name":"Problem","order":2,"description":"Uncover difficulties, dissatisfactions, and challenges.","signals":["Prospect expresses frustration","Mentions something that isn''t working"],"transition_cues":["A clear problem is identified","Prospect seems emotionally engaged with the issue"],"coaching_tips":["Ask about consequences — this transitions you to Implication","Don''t solve the problem yet"]},{"key":"implication","name":"Implication","order":3,"description":"Develop the seriousness of the problem by exploring consequences.","signals":["Prospect realizes the problem is bigger than they thought","Quantifies impact"],"transition_cues":["Prospect expresses urgency","Problem feels significant enough to warrant action"],"coaching_tips":["Connect the problem to revenue, reputation, or workload","Use chain-effect questions: if X happens, then what?"]},{"key":"need-payoff","name":"Need-Payoff","order":4,"description":"Get the buyer to articulate how a solution would help.","signals":["Buyer describes ideal state","Uses positive future-oriented language"],"transition_cues":["Buyer is ready for a proposal","Asks about next steps"],"coaching_tips":["Let the buyer do the talking — they should sell themselves","Summarize their stated benefits back to them"]}]'::jsonb,
  '[{"key":"situation","name":"Situation Questions","description":"Questions that gather factual background about the prospect''s current state.","purpose":"Establish context, but use sparingly.","examples":["How many picture days do you run per year?","Who currently handles your photography?"],"stage_affinity":["situation"],"difficulty":"beginner"},{"key":"problem","name":"Problem Questions","description":"Questions that uncover difficulties, frustrations, or dissatisfactions.","purpose":"Identify areas where your solution can add value.","examples":["What challenges do you face with your current photo process?","Are there complaints from parents about turnaround time?"],"stage_affinity":["problem"],"difficulty":"beginner"},{"key":"implication","name":"Implication Questions","description":"Questions that explore the consequences and effects of identified problems.","purpose":"Make the problem feel bigger and more urgent.","examples":["When parents are unhappy with photos, does that affect your online reviews?","What does it cost your staff in hours to coordinate picture day logistics?"],"stage_affinity":["implication"],"difficulty":"advanced"},{"key":"need-payoff","name":"Need-Payoff Questions","description":"Questions that get the buyer to articulate how a solution would help.","purpose":"Let the buyer sell themselves on the value.","examples":["If same-week online galleries were included, how would parents respond?","Would having a dedicated photographer free your staff to focus on the event?"],"stage_affinity":["need-payoff"],"difficulty":"intermediate"}]'::jsonb,
  '{"implicit need":"A vague dissatisfaction the buyer mentions but hasn''t fully developed.","explicit need":"A clear, specific desire for a solution that the buyer has articulated.","Situation question":"Gathers facts about the current state — necessary but low-value.","Problem question":"Uncovers difficulties or dissatisfactions.","Implication question":"Explores consequences to make problems feel serious.","Need-Payoff question":"Gets the buyer to state how a solution would benefit them.","SPIN ratio":"The proportion of I+N questions to S+P questions — higher is better."}'::jsonb,
  '[{"name":"Situation Question Overload","description":"Asking too many factual questions, making it feel like an interrogation.","detection_signals":["More than 3 situation questions in a row","Prospect giving short, bored answers"],"coaching_response":"You have enough background. Transition to a Problem question about what''s not working."},{"name":"Premature Solution","description":"Offering the solution before developing Implications and Need-Payoff.","detection_signals":["Pitching after Problem stage","Listing features before buyer feels urgency"],"coaching_response":"The buyer doesn''t feel the pain yet. Ask an Implication question about the consequences of this problem."},{"name":"Skipping Implication","description":"Jumping from Problem directly to Need-Payoff without developing urgency.","detection_signals":["Need-Payoff questions feel premature","Buyer isn''t engaged with the solution framing"],"coaching_response":"The problem needs to feel bigger first. Ask: What happens if this continues? How does it affect other areas?"}]'::jsonb,
  '[{"name":"Buyer Quantifies Problem Impact","description":"Prospect puts a number on the cost or consequence of their problem.","significance":"high"},{"name":"Buyer Describes Ideal Solution","description":"Prospect unpromptedly describes what they wish they had.","significance":"high"},{"name":"Chain-Effect Acknowledgment","description":"Prospect connects a problem to multiple downstream consequences.","significance":"medium"},{"name":"Buyer Asks How You Can Help","description":"Prospect invites the solution discussion.","significance":"high"}]'::jsonb,
  '[{"title":"Understand the four SPIN question types and their purpose","level":"beginner"},{"title":"Minimize Situation questions by researching prospects beforehand","level":"beginner"},{"title":"Develop implicit needs into explicit needs using Implication questions","level":"intermediate"},{"title":"Use Need-Payoff questions to let the buyer sell themselves","level":"intermediate"},{"title":"Achieve a high SPIN ratio (more I+N than S+P)","level":"advanced"}]'::jsonb,
  '[{"title":"The SPIN Sequence","summary":"Four question types in sequence: Situation → Problem → Implication → Need-Payoff. The order matters because each type builds on the previous.","key_takeaway":"Implication and Need-Payoff questions are the most powerful — spend most time here."},{"title":"Implicit vs Explicit Needs","summary":"An implicit need is a vague dissatisfaction. An explicit need is a clear want. Your job is to develop implicit into explicit using Implication questions.","key_takeaway":"Never present your solution until the buyer has expressed an explicit need."},{"title":"The Research Shortcut","summary":"The more you research beforehand, the fewer Situation questions you need — and the faster you get to value-creating questions.","key_takeaway":"Pre-call research on the studio/school replaces 80% of Situation questions."}]'::jsonb,
  'free', 'SPIN Selling is a registered trademark of Huthwaite International, now part of Korn Ferry. Used for educational reference.',
  'SPIN', 2, true
) ON CONFLICT (slug) DO NOTHING;

-- 3. Consultative Selling — Mack Hanan
INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'Consultative Selling', 'consultative-selling', 'Mack Hanan',
  'Position yourself as a trusted advisor who improves the customer''s business outcomes.',
  'Consultative Selling shifts the sales conversation from products and features to business impact and ROI. The salesperson becomes a trusted advisor who understands the customer''s business deeply enough to quantify the financial impact of their solution. The focus is on improving the customer''s profit, not on your product''s features.',
  'Three-phase approach: Understand the customer''s business and key metrics, Quantify the financial impact of problems and solutions, then Propose a business case (not a product pitch). Every recommendation ties back to the customer''s bottom line.',
  'Reps selling premium photography packages where ROI justification matters — e.g., multi-year contracts, exclusive partnerships, or studios comparing costs vs. in-house solutions.',
  '[]'::jsonb,
  '[{"title":"Consultative Selling","author":"Mack Hanan","year":2011,"url":"https://www.amazon.com/Consultative-Selling-8th-Mack-Hanan/dp/0814437508"}]'::jsonb,
  'handshake', 'mindset', 5, 'intermediate',
  ARRAY['consultative','roi','business-impact','trusted-advisor','volume-photography'],
  E'You are a sales coach specializing in Mack Hanan''s Consultative Selling methodology, applied to volume photography B2B sales.\n\nCore principle: You are not selling photography services — you are improving the customer''s business. Every conversation must connect to the customer''s financial outcomes.\n\nThree phases:\n1. UNDERSTAND — Learn the customer''s business model, key metrics, and pain points. For a dance studio: How many students? Average revenue per event? How do they market to parents? What''s their retention rate?\n2. QUANTIFY — Put numbers on the problem and solution. "If 200 families attend your recital and only 30% buy photos from your current vendor, that''s 140 families with no professional photos. Our average is 70% purchase rate — that''s an additional $X in parent satisfaction and $Y in photo revenue share."\n3. PROPOSE — Present a business case, not a product pitch. "Based on your 4 events per year and 200 families, partnering with us would generate approximately $X in additional revenue and save your staff Y hours per event."\n\nKey coaching rules:\n- Always quantify. Vague value statements are not consultative selling.\n- Position yourself as a profit-improver, not a vendor.\n- Speak in the customer''s metrics: enrollment, retention, parent satisfaction, revenue per event.',
  '{"practice_mode":"Role-play scenarios where the user must calculate and articulate ROI for photography services. Evaluate whether they quantify impact vs just describe features.","live_call":"Listen for feature-dumping and redirect to business impact. Suggest financial framing when the rep describes capabilities.","call_analyzer":"Score on how well the rep quantified business impact. Flag feature-focused statements that should have been ROI statements.","email_composer":"Frame outreach around business results, not service features. Include specific numbers or ranges when possible."}'::jsonb,
  '[{"key":"business_acumen","name":"Business Acumen","description":"Does the rep demonstrate understanding of the customer''s business model and metrics?","weight":0.30,"anchors":{"1":"No business context discussed","3":"Some business understanding but surface level","5":"Deep understanding of customer''s revenue drivers, costs, and KPIs"}},{"key":"roi_articulation","name":"ROI Articulation","description":"Can the rep quantify the financial impact of the solution?","weight":0.25,"anchors":{"1":"No numbers mentioned","3":"Vague value statements","5":"Specific, calculated ROI with clear assumptions"}},{"key":"trust_building","name":"Trust Building","description":"Does the rep come across as a trusted advisor vs a vendor?","weight":0.25,"anchors":{"1":"Pure sales pitch","3":"Some advisory moments mixed with pitching","5":"Consistently positions as business partner focused on customer outcomes"}},{"key":"solution_alignment","name":"Solution Alignment","description":"Is the proposed solution clearly tied to the customer''s stated business needs?","weight":0.20,"anchors":{"1":"Generic pitch regardless of needs","3":"Some customization","5":"Solution is entirely framed around customer''s specific challenges and goals"}}]'::jsonb,
  '[{"key":"understand","name":"Understand","order":1,"description":"Learn the customer''s business model, metrics, and challenges.","signals":["Customer shares financial details","Discusses strategic goals","Opens up about internal challenges"],"transition_cues":["You can articulate the customer''s key metrics","You understand what drives their revenue"],"coaching_tips":["Ask about their business model, not just their photography needs","Learn their KPIs: enrollment, retention, event revenue"]},{"key":"quantify","name":"Quantify","order":2,"description":"Put numbers on both the problem and the potential solution.","signals":["Customer engages with the numbers","Validates or corrects your assumptions"],"transition_cues":["A clear financial case is emerging","Customer agrees with the impact assessment"],"coaching_tips":["Use their numbers, not yours","Build the business case together — don''t present it unilaterally"]},{"key":"propose","name":"Propose","order":3,"description":"Present a business case tied to the customer''s specific outcomes.","signals":["Customer asks about implementation","Discusses timelines and logistics"],"transition_cues":["Customer is ready for a formal proposal","Asks to involve other decision makers"],"coaching_tips":["Lead with the ROI, not the service details","Frame it as a joint business improvement, not a sale"]}]'::jsonb,
  '[]'::jsonb,
  '{"profit improvement":"The quantifiable financial gain your solution delivers to the customer.","business case":"A structured argument for the solution based on customer''s own financial metrics.","trusted advisor":"A seller who is valued for business insight, not just product knowledge.","ROI framing":"Presenting your solution in terms of return on investment rather than features.","customer''s metrics":"KPIs that matter to the buyer: enrollment, retention, revenue per event, staff hours."}'::jsonb,
  '[{"name":"Feature Dumping","description":"Listing product features instead of connecting to business outcomes.","detection_signals":["Multiple consecutive feature descriptions","No mention of customer ROI or metrics"],"coaching_response":"Stop listing features. Connect this capability to their bottom line: How does this improve their enrollment or parent satisfaction?"},{"name":"Vague Value Claims","description":"Saying things like ''we provide great value'' without quantifying.","detection_signals":["Words like great, best, amazing without numbers","No specific ROI calculation"],"coaching_response":"Quantify it. Instead of ''great photos,'' say: ''Studios using our service see a 70% parent purchase rate vs the industry average of 30%.''"},{"name":"Vendor Positioning","description":"Acting like a service provider taking orders instead of a business partner.","detection_signals":["Only responding to customer questions","Not offering strategic insight"],"coaching_response":"Shift from order-taker to advisor. Share an insight about their industry they may not know."}]'::jsonb,
  '[{"name":"Customer Shares Financial Data","description":"Prospect reveals revenue figures, costs, or budget numbers.","significance":"high"},{"name":"Customer Co-Builds the Business Case","description":"Prospect actively participates in calculating ROI.","significance":"high"},{"name":"Customer References Your Insight","description":"Prospect repeats or references a business insight you shared.","significance":"medium"},{"name":"Customer Asks for a Proposal","description":"Prospect requests a formal business case document.","significance":"high"}]'::jsonb,
  '[{"title":"Shift from product-selling to profit-improving mindset","level":"beginner"},{"title":"Learn to ask about business metrics, not just photography needs","level":"beginner"},{"title":"Quantify the financial impact of your photography service","level":"intermediate"},{"title":"Build and present a customer-specific business case","level":"intermediate"},{"title":"Position yourself as a trusted advisor, not a vendor","level":"advanced"}]'::jsonb,
  '[{"title":"Profit Improvement, Not Product Selling","summary":"Consultative Selling reframes the entire sales conversation around the customer''s profit. You are not a photographer — you are a business partner who improves their bottom line.","key_takeaway":"Every recommendation must tie to a specific financial outcome for the customer."},{"title":"The Power of Quantification","summary":"Vague value claims don''t close deals. Specific numbers do. Calculate the difference between their current state and what you deliver.","key_takeaway":"If you can''t quantify the impact, you haven''t done enough discovery."},{"title":"Business Case vs Sales Pitch","summary":"A sales pitch describes your service. A business case describes the customer''s improved future with numbers to prove it.","key_takeaway":"Present a one-page business case instead of a capabilities deck."}]'::jsonb,
  'free', 'Consultative Selling is a methodology developed by Mack Hanan. Used for educational reference.',
  'CS', 3, true
) ON CONFLICT (slug) DO NOTHING;

-- 4. Gap Selling — Keenan
INSERT INTO methodologies (name, slug, author, tagline, description, how_it_works, best_for, videos, books, icon, category, relevance_rating, complexity_level, tags, system_prompt_template, feature_prompt_overrides, scoring_rubric, stages, question_types, vocabulary, anti_patterns, success_signals, learning_objectives, concept_chunks, access_tier, trademark_attribution, known_as, sort_order, is_active)
VALUES (
  'Gap Selling', 'gap-selling', 'Keenan',
  'Identify the gap between the customer''s current state and desired future state.',
  'Gap Selling focuses on understanding the delta between where the customer is now (current state) and where they want to be (future state). The bigger the gap, the more urgency to buy. The salesperson''s job is to accurately diagnose the current state problems, paint a compelling future state, and quantify the gap in terms the buyer cares about.',
  'Three phases: diagnose the Current State thoroughly (facts, problems, and the impact of those problems), define the Future State in vivid detail, then Quantify the Gap so the buyer sees exactly what they''re losing by not acting. The sale happens when the gap feels too big to ignore.',
  'Reps who encounter prospects saying "we''re fine with what we have" — Gap Selling is designed to create urgency where none exists by making the invisible gap visible.',
  '[]'::jsonb,
  '[{"title":"Gap Selling","author":"Keenan","year":2018,"url":"https://www.amazon.com/Gap-Selling-Everything-Problem-Centric-Conversation/dp/1732891001"}]'::jsonb,
  'git-compare', 'mindset', 4, 'intermediate',
  ARRAY['gap-analysis','current-state','future-state','urgency','change-management','volume-photography'],
  E'You are a sales coach specializing in Keenan''s Gap Selling methodology, applied to volume photography B2B sales.\n\nCore principle: People don''t buy products — they buy the solution to a gap between where they are and where they want to be. Your job is to make that gap vivid and measurable.\n\nThree phases:\n1. CURRENT STATE — Diagnose thoroughly. What is the prospect''s actual situation today? For a dance studio: Who does their photos? What''s the quality? What do parents say? How much staff time does it take? What''s the revenue from photos? What are the problems and what''s the business impact of those problems?\n2. FUTURE STATE — What does the ideal look like? "Imagine every family gets a beautiful online gallery within 48 hours, your staff spends zero time on photo logistics, and you earn a revenue share on every purchase. What would that mean for your business?"\n3. GAP QUANTIFICATION — Make the gap tangible. "Right now you''re getting $2 per student from photo revenue with 30% parent satisfaction. The future state is $8 per student with 85% satisfaction. That''s a $6 per student gap across 500 students = $3,000 per year you''re leaving on the table."\n\nKey coaching rules:\n- Never accept "we''re fine" at face value — dig deeper into the current state.\n- The prospect must feel the gap emotionally, not just intellectually.\n- The bigger the gap, the faster the sale.\n- Always quantify the gap in the buyer''s own terms.',
  '{"practice_mode":"Role-play scenarios where the prospect starts with ''we''re happy with our current photographer.'' Score on how well the user diagnoses the current state and makes the gap visible.","live_call":"Track whether the rep is in current-state, future-state, or gap-quantification mode. Alert when they skip current-state diagnosis.","call_analyzer":"Map the conversation to the three phases. Score on depth of current-state diagnosis and specificity of gap quantification.","email_composer":"Use current state → future state contrast in outreach emails. Highlight the gap studios may not realize they have."}'::jsonb,
  '[{"key":"current_state_diagnosis","name":"Current State Diagnosis","description":"How thoroughly does the rep explore the prospect''s current situation, problems, and their impact?","weight":0.30,"anchors":{"1":"Superficial or no current state exploration","3":"Some problems identified but impact not explored","5":"Thorough diagnosis of facts, problems, and quantified business impact"}},{"key":"future_state_vision","name":"Future State Vision","description":"Can the rep paint a compelling picture of the desired future?","weight":0.25,"anchors":{"1":"No future state discussed","3":"Generic future state","5":"Vivid, specific future state that resonates with buyer''s priorities"}},{"key":"gap_quantification","name":"Gap Quantification","description":"Is the gap between current and future states quantified in meaningful terms?","weight":0.25,"anchors":{"1":"No gap quantification","3":"Vague comparison","5":"Specific, numerical gap that makes inaction feel costly"}},{"key":"urgency_creation","name":"Urgency Creation","description":"Does the buyer feel compelled to act based on the gap identified?","weight":0.20,"anchors":{"1":"No urgency — buyer is comfortable with status quo","3":"Some discomfort but no action commitment","5":"Buyer feels the gap is too costly to ignore and wants to act now"}}]'::jsonb,
  '[{"key":"current-state","name":"Current State","order":1,"description":"Thoroughly diagnose the prospect''s existing situation, problems, and their impact.","signals":["Prospect describes their situation in detail","Acknowledges problems they hadn''t fully considered"],"transition_cues":["You can describe their current state better than they can","Business impact of problems is clear"],"coaching_tips":["Don''t accept surface answers — dig into the impact","Ask: What does this problem cost you in time, money, or satisfaction?","Document facts AND emotions about the current state"]},{"key":"future-state","name":"Future State","order":2,"description":"Define what the ideal situation looks like in vivid, specific terms.","signals":["Prospect engages with the vision","Adds their own details to the future picture"],"transition_cues":["Both you and the prospect agree on the ideal outcome","The contrast with current state is stark"],"coaching_tips":["Use the prospect''s own language to describe the future","Make it concrete — specific numbers, timelines, outcomes","Let them co-create the vision"]},{"key":"gap-quantification","name":"Gap Quantification","order":3,"description":"Calculate and present the difference between current and future state.","signals":["Prospect is struck by the size of the gap","Uses phrases like ''I didn''t realize'' or ''that''s significant''"],"transition_cues":["The gap feels too large to ignore","Prospect wants to discuss how to close it"],"coaching_tips":["Use their metrics and their numbers","Present the gap per year to make it feel larger","Ask: Is this gap worth closing?"]}]'::jsonb,
  '[]'::jsonb,
  '{"current state":"The prospect''s actual, present-day situation including facts, problems, and their business impact.","future state":"The ideal situation the prospect wants to achieve.","the gap":"The measurable delta between current state and future state.","gap quantification":"Expressing the gap in concrete terms (dollars, hours, satisfaction scores) that make inaction feel costly.","status quo bias":"The tendency to stay with what''s familiar even when it''s suboptimal — Gap Selling is designed to overcome this."}'::jsonb,
  '[{"name":"Accepting We''re Fine","description":"Taking the prospect''s ''we''re happy with what we have'' at face value without probing.","detection_signals":["Moving on after the prospect says they''re satisfied","Not exploring the current state deeply"],"coaching_response":"Don''t accept that yet. Ask: What would picture day look like if you could design it from scratch? The gap between ''fine'' and ''ideal'' is where the sale lives."},{"name":"Skipping Current State","description":"Jumping to the future state or solution without diagnosing the present.","detection_signals":["Painting the future without understanding today","Proposing solutions before understanding problems"],"coaching_response":"Slow down. You need to understand their current state thoroughly first. Ask about their last picture day — what worked and what didn''t?"},{"name":"Unquantified Gap","description":"Describing the gap qualitatively but not putting numbers on it.","detection_signals":["Using words like better, faster, easier without numbers","No financial or metric-based comparison"],"coaching_response":"Quantify the gap. How many families? What percentage improvement? What''s the dollar value of closing this gap?"}]'::jsonb,
  '[{"name":"Prospect Says I Didn''t Realize","description":"Prospect expresses surprise at the size of the gap.","significance":"high"},{"name":"Prospect Co-Creates the Future State","description":"Prospect adds their own ideas to the future vision.","significance":"high"},{"name":"Prospect Asks How to Close the Gap","description":"Prospect moves from diagnosis to solution-seeking.","significance":"high"},{"name":"Prospect Recalculates Their Own Situation","description":"Prospect starts doing their own math on the gap.","significance":"medium"}]'::jsonb,
  '[{"title":"Understand the three phases: Current State, Future State, Gap Quantification","level":"beginner"},{"title":"Learn to diagnose the current state beyond surface-level answers","level":"beginner"},{"title":"Paint compelling, specific future state visions for photography clients","level":"intermediate"},{"title":"Quantify gaps using the prospect''s own metrics and language","level":"intermediate"},{"title":"Overcome status quo bias by making the invisible gap visible","level":"advanced"}]'::jsonb,
  '[{"title":"Current State Is King","summary":"Most sales reps spend too little time on current state. Gap Selling insists you diagnose thoroughly — facts, problems, and the impact of those problems — before moving forward.","key_takeaway":"You can''t quantify a gap you haven''t fully diagnosed."},{"title":"The Bigger the Gap, the Faster the Sale","summary":"Urgency is not created by pressure tactics — it''s created by making the gap feel too large to ignore. When the prospect sees a $3,000/year gap, they want to close it.","key_takeaway":"Always express the gap in annual or per-event terms to maximize perceived impact."},{"title":"Overcoming ''We''re Fine''","summary":"The most common objection in B2B sales. Gap Selling handles it by exploring what ''fine'' actually looks like — and revealing that ''fine'' is far from ''ideal.''","key_takeaway":"''We''re fine'' is the start of the conversation, not the end."}]'::jsonb,
  'pro', 'Gap Selling is a methodology developed by Keenan of A Sales Growth Company. Used for educational reference.',
  'GS', 4, true
) ON CONFLICT (slug) DO NOTHING;
